version: "3.8"
services:
  # 배치서버
  statistics-processing-server:
    image: solmin2/statistics-processing-server:latest
    container_name: statistics-processing-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile # dockerfile : 도커파일 경로
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    volumes:  
      - ./dev-logs:/app/logs # 로컬 디렉토리 하위의 ./dev-data와 컨테이너 안의 /data/db를 매핑
  # 몽고DB
  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:  
      - ./dev-data:/data/db # 로컬 디렉토리 하위의 ./dev-data와 컨테이너 안의 /data/db를 매핑
    env_file:
      - mongo.env