version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.2.1-20220531
    container_name: selenium_hub
    ports:
      - 4442-4444:4442-4444
    networks:
      - grid

  chrome-node:
    image: selenium/node-chrome:4.2.1-20220531
    container_name: chrome_node
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    networks:
      - grid

networks:
  grid:
    driver: bridge
